# Generated by Django 6.0 on 2025-12-29 17:45

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FerramentaBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RotinaBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("descricao", models.CharField(max_length=200)),
                (
                    "frequencia",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Diário"),
                            ("SEMANAL", "Semanal"),
                            ("MENSAL", "Mensal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("horario_execucao", models.TimeField()),
                ("retencao_dias", models.IntegerField()),
                (
                    "ferramenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backups.ferramentabackup",
                    ),
                ),
                (
                    "servidores",
                    models.ManyToManyField(
                        related_name="rotinas", to="clientes.servidor"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValidacaoBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCESSO", "✅ Sucesso"),
                            ("ALERTA", "⚠️ Alerta"),
                            ("ERRO", "❌ Erro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "evidencia",
                    models.FileField(
                        upload_to=apps.common.validators.evidence_upload_path,
                        validators=[apps.common.validators.validate_file_infection],
                    ),
                ),
                (
                    "rotina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backups.rotinabackup",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
