# Generated by Django 6.0 on 2025-12-29 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validacaobackup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Validação de Backup', 'verbose_name_plural': 'Validações de Backup'},
        ),
        migrations.AddField(
            model_name='validacaobackup',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes_editadas', to=settings.AUTH_USER_MODEL, verbose_name='Editado por'),
        ),
        migrations.AlterField(
            model_name='validacaobackup',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validacoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
