# Generated by Django 6.0 on 2025-12-30 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_alter_validacaobackup_options_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotinabackup',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='clientes.cliente'),
        ),
    ]
