# Generated by Django 6.0 on 2025-12-31 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_rotinabackup_cliente'),
        ('clientes', '0002_alter_cliente_cnpj_alter_cliente_contato_tecnico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferramentabackup',
            options={'verbose_name': 'Ferramenta', 'verbose_name_plural': 'Ferramentas'},
        ),
        migrations.AlterModelOptions(
            name='rotinabackup',
            options={'verbose_name': 'Rotina de Backup', 'verbose_name_plural': 'Rotinas de Backup'},
        ),
        migrations.AlterModelOptions(
            name='validacaobackup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Validação Realizada', 'verbose_name_plural': 'Validações Realizadas'},
        ),
        migrations.AddField(
            model_name='rotinabackup',
            name='conteudo',
            field=models.CharField(default='Servidor Completo', help_text='Ex: Servidor Completo, Pasta de Dados, Banco SQL, C:/Arquivos...', max_length=255, verbose_name='O que está sendo copiado?'),
        ),
        migrations.AlterField(
            model_name='rotinabackup',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Nome da Rotina'),
        ),
        migrations.AlterField(
            model_name='rotinabackup',
            name='ferramenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backups.ferramentabackup', verbose_name='Ferramenta'),
        ),
        migrations.AlterField(
            model_name='rotinabackup',
            name='frequencia',
            field=models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], max_length=20, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='rotinabackup',
            name='servidores',
            field=models.ManyToManyField(related_name='rotinas', to='clientes.servidor', verbose_name='Servidores'),
        ),
    ]
