# Generated by Django 6.0 on 2025-12-31 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato_tecnico',
            field=models.CharField(max_length=100, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_contato',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(max_length=150, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='clientes.cliente', verbose_name='Servidores'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='hostname',
            field=models.CharField(max_length=100, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='sistema_operacional',
            field=models.CharField(max_length=100, verbose_name='Sistema Operacional'),
        ),
    ]
